brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
enum_discrim_align_threshold = 30
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
spaces_around_ranges = true
struct_field_align_threshold = 30
wrap_comments = true
